[project]
name = "detectormanos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.9.*"  # Forzar Python 3.9
dependencies = [
    "opencv-python>=4.12.0.88",
    "mediapipe==0.8.3.1",      # VersiÃ³n antigua de MediaPipe
]